### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by DominiqueMakowski** [titoghose/PyTrack#1]
You guys should strive at setting the repo "right" before it starts to get complicated. By that, I mean setting up continuous integration (travis, codecoverage, codacy etc.) and automatic documentation. These things only get more complicated to get right once the package is getting thicker.

There are some nice templates out there, e.g., https://github.com/audreyr/cookiecutter-pypackage

**Comment by titoghose** [comment]
Thanks for the tip Dom. We'll look into it and get it in place.
