### ISSUE TITLE
PyTrack installation error on Mac

### ISSUE THREAD

**Issue by fahed4in** [titoghose/PyTrack#5]
Hi Team,
I hope all is well.
I am getting the below error while installing PyTrack on Mac, did follow all three installation commands but the issue still persists.
Can you please advise if the issue is related to my libraries on my computer?many thanks for your help.

_ERROR: Command errored out with exit status 1: /Users/nyuad/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/n5/zqp4rcj533b87g6bdpq5gw700000gn/T/pip-install-buhrt9j8/scipy_be22f1e7a1d649508774b44236c64b21/setup.py'"'"'; __file__='"'"'/private/var/folders/n5/zqp4rcj533b87g6bdpq5gw700000gn/T/pip-install-buhrt9j8/scipy_be22f1e7a1d649508774b44236c64b21/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/n5/zqp4rcj533b87g6bdpq5gw700000gn/T/pip-record-yiytzq8z/install-record.txt --single-version-externally-managed --compile --install-headers /Users/nyuad/opt/anaconda3/include/python3.8/scipy Check the logs for full command output._

Detailed error in this file:
[detailed error.txt](https://github.com/titoghose/PyTrack/files/5862582/detailed.error.txt)

**Comment by fahed4in** [comment]
And attached the error when executed python3 setup.py install command to install.
[error when used python3 setup.py install.txt](https://github.com/titoghose/PyTrack/files/5865662/error.when.used.python3.setup.py.install.txt)

**Comment by titoghose** [comment]
The issue has now been resolved

**Comment by fahed4in** [comment]
It worked.
Many thanks, Titoghose.

**Comment by wsojka00** [comment]
Hello, I've encountered the same problem on Windows. Do you have any idea how to solve it?

**Comment by fahed4in** [comment]
Hi,for me I have re-downloaded the file and compiled it, it worked.Haven't tried this on Windows but give it a try compiling using git bash. 

Thanks & Regards,Mohammed Fahed 

    On Wednesday, February 16, 2022, 06:11:57 PM GMT+4, Weronika Sójka ***@***.***> wrote:  
 
 


Hello, I've encountered the same problem on Windows. Do you have any idea how to solve it?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
