### ISSUE TITLE
PyTrack installation error on Windows

### ISSUE THREAD

**Issue by siqiyaoyao** [titoghose/PyTrack#6]
Hi Team,
I am really interested in this analysis tool. But I had a problem with the installation. I'm not sure whether is related to the installation problem mentioned before. Just attach the error details. 

Looking forward to your new version!

[windows.txt](https://github.com/titoghose/PyTrack/files/6736880/windows.txt)

**Comment by titoghose** [comment]
The issue has now been resolved. Please try and install it now.
